name: tedjdesign
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress:
  flutter_native_splash: ^1.2.0
  flutter_cache_manager: ^3.3.1
  hive: 
  hive_flutter: 
  image_picker: ^1.0.2
  liquid_pull_to_refresh: ^3.0.1
  permission_handler: ^10.4.3
  file_picker: ^5.3.4
  get:
  intl: ^0.18.1
  flutter_screenutil:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0

flutter_app_name:
  name: "GYM SOF"
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gym.png"
  min_sdk_android: 21
  hive_generator: 
  build_runner: 
  flutter_lints: ^2.0.0
  flutter_native_splash: ^1.2.0
flutter_native_splash:
  android: true
  ios: false
  web: false
  background_image: "assets/splash.png"
flutter:
  uses-material-design: true
  assets:
    - assets/